config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: 'accounts'

  resources :users do
    resources :items
  end

  authenticated :user do
    root to: 'users#show', as: :authenticated_root
  end

  unauthenticated :user do
    root 'welcome#index', as: :unauthenticated_root
  end

  get 'about' => 'welcome#about'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  before_create :set_expiration_date
  belongs_to :user

  def set_expiration_date

    self.expires_at = Time.now + rand(1..7).days if expires_at.nil?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

  before_save { self.role ||= :member }

  enum role: [:member, :premium, :admin]

  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(user)
    current_user
  end

  def after_sign_out_path_for(user)
    root_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :all_items, only: [:index, :create, :destroy]
  respond_to :html, :js

  def new
    @item = Item.new
    @user = current_user
  end

  def create
    @item = current_user.items.create(item_params)

    if @item.save
      puts 'Success!'
    else
      puts 'Error'
      format.json{ render json: @item.errors.full_messages, status: :unprocessable_entity}
      puts @item.inspect
    end
  end

  def destroy
    @item = Item.find(params[:id])

    @item.destroy
    respond_to do |f|
      f.html { redirect_to root }
      f.js
    end
  end

  private

  def all_items
    @items = Item.all
    @user = current_user
  end

  def item_params
    params.require(:item).permit(:user_id, :name, :expires_at, :created_at)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def get_expiring_alert_color(expires_in)
    case expires_in
    when '6 days', '7 days'
      'alert-success'
    when '4 days', '5 days'
      'alert-info'
    when '2 days', '3 days'
      'alert-warning'
    else
      'alert-danger'
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_with model: [@user,@item], class: 'new_item_form' do |f| %>
  <%= f.text_field :name, maxlength: 15 %>
  <%= f.button :submit %>
<% end %>

app/views/items/_item.html.erb
<div class="col-md-4 col-sm-12 text-center todo_item" draggable="true">
  <div class="panel panel-primary panel-shadow no-overflow">
    <div class="panel-heading">
      <div class="row">
        <div class="col-sm-2">
          <%= link_to user_item_url(id: item.id, user_id: @user.id), method: :delete, remote: true do %>
          <i class="fas fa-check fa-3x toggle_task task_complete"></i>
            <% end %>
        </div>
        <div class="col-sm-10">
          <div class="font-2x text-center"><%= item.name %></div>
          <div class="alert <%= get_expiring_alert_color(time_ago_in_words(item.expires_at)) %> text-center no-pad">Expires in <%= distance_of_time_in_words(Time.now, item.expires_at) %>.</div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/create.js.erb
$('#items').html("<%= j (render @items) %>");
$('#total_items').html("<i class='far fa-square fa-fw'></i> Items: <%= @user.items.all.count %>");
$('#todo_form').slideUp(350);
$('#new_todo_name').val('');

app/views/items/destroy.js.erb
$('#items').html("<%= j (render @items) %>");

app/views/items/new.js.erb
$('#todo_form').html("<%= j (render 'form') %>");
$('#todo_form').slideDown(350);
$('#todo_form input').focus();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GetItDone</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Farsan|Pacifico" rel="stylesheet">

    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggled="collapse" data-target="navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle Navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <% if user_signed_in? %>
              <%= link_to 'GetItDone', authenticated_root_path, class: 'navbar-brand pacifico' %>
            <% else %>
              <%= link_to 'GetItDone', unauthenticated_root_path, class: 'navbar-brand pacifico' %>
            <% end %>
          </div>

          <div class="collapse navbar-collapse" id="navbar-collapse-1">
            <ul class="nav navbar-nav navbar-left">
              <li class="active"><%= link_to 'GitHub Repo', 'https://github.com/mdavis93/GetItDone', target: '_blank' %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if !user_signed_in? %>
                <li><a href="#">Features</a></li>
                <li><a href="#">Premium</a></li>
                <li><%= link_to "Log In", new_user_session_path %></li>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <% else %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-plus"><small><span class="glyphicon glyphicon-triangle-bottom"></span></small></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">New ToDo List</a>
                    <li><a href="#">Link</a>
                  </ul>
                </li>

                <p class="navbar-text"><%= current_user.email %></p>

                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-cog"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "My Profile", edit_user_registration_path %></li>
                    <li><a href="#">Refer A Friend</a></li>
                    <li><a href="#">Send a Bookmark</a></li>
                    <li role="separator" class="divider"></li>
                    <li>
                      <%= link_to destroy_user_session_path, method: :delete do %>
                        <span class="glyphicon glyphicon-log-out"></span> Log Out
                      <% end %>
                    </li>
                  </ul>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>

      <% if flash[:notice] %>
        <div class="alert alert-success" id="flash_msg">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger" id="flash_msg">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <% if current_user %>
      <div class="panel panel-info no-overflow">
        <div class="panel-heading">
          <div class="panel-title text-center">
            <h1>Welcome Back, <%= @username %>!</h1>
          </div>
        </div>
        <div class="panel-body">
          <div class="col-md-4">
            <h6>Your last visit was <%= time_ago_in_words(@user.last_sign_in_at) %> ago.</h6>
            <p><i class="fas fa-key fa-fw"></i> <%= link_to 'Change Your Password', edit_user_registration_path %></p>
            <p id="total_items"><i class="far fa-square fa-fw"></i> Items: <%= @user.items.all.count %></p>
            <p><i class="fas fa-times fa-fw text-danger"></i>Expiring Items: <%= @user.items.all.where('expires_at < ?', Time.now + 2.days).count %></p>
          </div>
          <div class="col-md-4 border-left-dashed border-right-dashed">
            <h3 class="text-center mar-top-0">New To-Do Task</h3>
            <p class="text-justify">To create a new task item, enter the name below and click <strong>[SUBMIT]</strong> or press <strong>[ENTER]</strong>.  All tasks will expire seven days after creation.</p>
            <div class="col-sm-12 text-center todo_item new_item">
              <div class="panel panel-primary panel-shadow no-overflow">
                <div class="panel-heading">
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="font-2x">
                        <%= form_with model: [@user,@item] do |f| %>
                          <div class="input-group">
                            <%= f.text_field :name, maxlength: 18, id: 'new_todo_name', class: 'form-control input-lg' %>
                            <span class="input-group-btn">
                              <%= f.button :submit, class: 'btn btn-lg btn-default' %>
                            </span>
                          </div>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="container todo-group">
  <div class="row">
    <div class="col-xs-12">
      <h1>Your Tasks</h1>
    </div>
  </div>
  <div class="row">
    <div id="items">
      <%= render @items %>
    </div>
  </div>
</div>

app/views/welcome/about.html.erb
<div class="row">
  <div class="col-md-6 col-xs-12">
    <%= image_tag('svg/weekly_calendar.svg', width: '100%') %>
  </div>
  <div class="col-md-6 col-xs-12">
    <h1>GetItDone Premium</h1>
    <h4>
      <ul>
        <li>Email reminders every 24 hours</li>
        <li>Invite others to view and/or manage your list(s)</li>
        <li>Synchronize with your favorite mail program</li>
        <li>Have Watson do your tasks for you!</li>
        <li>... and MORE!</li>
      </ul>
    </h4>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="row">
  <section class="section_container clearfix">
    <div class="col-md-6">
      <div class="row">
        <div class="col-md-12 text-center" id="main_logo_box">
          <h1 class="pacifico">GetItDone</h1>
          <h3 class="farsan">The Self Destructing ToDo List!</h3>
        </div>
      </div>
      <div class="row">
        <div class="row working_demo_callout">
          <div class="col-md-2">
            <i class="fab fa-expeditedssl fa-3x"></i>
          </div>
          <div class="col-md-10">
            <p>To login and explore this working demo, login with:<br>
              Email: <code>test@getitdone.com</code><br>
              Password: <code>helloworld</code></p>
          </div>
        </div>
        <div class="col-md-12">
          <p>Are you always rewriting your ToDo Lists? Are they filled with things you'll never get to?  Or is your list filled with tasks you'll never "have time for"?  Let <strong><em>GetItDone</em></strong> help you out!  With our ToDo List, your tasks will SELF DESTRUCT after seven days.  No more hunting through pointless tasks to get to the important things that need to be done!</p>
          <%= link_to "Sign Up Today!", new_user_registration_path, class: "btn btn-lg btn-primary btn-block", role: "button" %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <%= image_tag('svg/todo_clipboard_check.svg', style: "max-width: 80%") %>
    </div>
  </section>
  <section class="clearfix">
    <div class="col-md-6 col-md-offset-3" id="sample_todo">
      <h1>ToDo List</h1>
      <hr>
        <p><span class="glyphicon glyphicon-check" aria-hidden="true"></span> Find <span class="pacifico">GetItDone</span>.</p>
      <p><span class="glyphicon glyphicon-check" aria-hidden="true"></span> Be amazed!</p>
      <p><span class="glyphicon glyphicon-check" aria-hidden="true"></span> Sign Up For Awesomeness!</p>
      <p><span class="glyphicon glyphicon-check" aria-hidden="true"></span> Become a maven at getting things done!</p>
    </div>
  </section>
</div>